### PR TITLE
Adding the 'dots' command

### PR DESCRIPTION
**Pull request by xekoukou**
Have a look at this. Tell me your opinion. There are examples in the tests.
(dots.js.dna)

### CODE REVIEW

**Comment by sustrik** [comment]
I don't like how it sacrifices readability to get the feature. If you look at any specific line of code you can't tell in which compilation it will be processed unless you've scaned all the code above for occurences of 'dots' command.

I would really prefer to have /!include("foo.dna", 3) thing.

Advantages:

1. Each file has consistent 'dotting'.
2. Single file can be re-used in different contexts each with different number of dots.

Caveats:

- Requires multiple files where otherwise one would suffice.

Implementation note:

1. Lines with no dot should be escaped (e.g. "@{" --> "@{at}{")
2. Lines with dot should increase all nesting levels (e.g. "@2{}" -> "@3{}")

**Comment by xekoukou** [comment]
From the advantages only 1. is correct.

2. cannot happen because you need the correct number of dots to exist for the part that will go to the last output file anyway. See the tests.

That is why you do not need to track the ./dots commands. If you know the number of levels/ribosome executions that are required (e) , then by looking at the dots(n) of a line that doesn't have javascript written in it, your level is e-n-1.

So it is easy to deduce it without looking at the dots commands. Check the tests to understand what I mean.

**Comment by xekoukou** [comment]
I will use this for my projects till you decide what is best for ribosome. When you implement it, I will implement it for javascript as well.

**Comment by xekoukou** [comment]
Nested expressions now are relative to the current dotbase level.

I added an execution command of the form:
```
./exec("filepath",[arg1 , arg2, arg3],[array of args])
```

Each array of args is given to the ribosome.js for every step of compilation.

This is necessary when you include metalibraries into your project and you want to compile them at the level that your code can find them useful.
By compiling them at a certain level, their levels do not interfere with each other. Each library has different requirements for number of dots.

**Pull request closed without merging**
