### PR TITLE
Various compatibility fixes, test system cleanup

### PR DESCRIPTION
**Pull request by jaseg**
Hi,

here are a three things:
 * Compatibility fixes for python 3
 * Fix for non-ubuntu nodejs setups (on most other distros, nodejs is just "node")
 * Replace autotools stuff with something lean and make-based
If you like, I can split this up into separate PRs.

Regards, jaseg

### CODE REVIEW

**Comment by sustrik** [comment]
Looks nice.

What are we going to do with node/nodejs thing though? I've opted for 'node' because it's what the developers named the thing, assuming that people on nodejs systems can make a symbolic link.

Can we somehow support both?

Also, please state that the patch is submitted under MIT license.

**Comment by jaseg** [comment]
This patch is BSD-licensed.

Ribosome actually used "nodejs" instead of "node". The "official" variant seems to be "node", as that is what they use on https://nodejs.org/ . It would be possible to brute-force the nodejs path in the test scripts, but there does not seem to be a fix for the shebang line. I would favor sticking to nodejs.org and let distros cope with the specifics. E.g. on Ubuntu, that should be `# update-alternatives node`.

**Comment by xekoukou** [comment]
I agree. Let's stick to "node".

**Comment by sustrik** [comment]
Ok, fair enough. Coupla of additional points:

- color codes don't seem to work in my shell (bash):

Running python2 tests.
[\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] 
Running python3 tests.
[\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] 
Running ruby tests.
[\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] 
Running node tests.
[\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m] [\033[92mOK\033[0m]

- what name and email address should I add to AUTHORS file?

**Comment by jaseg** [comment]
I just pushed a fix for the color codes. The problem is that the builtin echo in dash does not have an "-e" option, but the one in bash does. So I'm now just using the system echo binary that in most cases (I hope) will have this option.

For the AUTHORS file, `jaseg <github@jaseg.net>` is fine.

**Comment by sustrik** [comment]
Great, the colouting works for me now.

Do you mind putting your real name in? AFAIK the copyright claim cannot be done with nick. And without the underlying copyright, the license doesn't work (the license means that you, as the owner of the copyright are granting some rights).

**Comment by jaseg** [comment]
Ok, then `Sebastian Götte <github@jaseg.net>` should be fine.

**Comment by sustrik** [comment]
Merged. Thanks!

**Pull request merged**
